# frozen_string_literal: true

require "spec_helper"
require_relative "../../lib/whodunit/generator"

RSpec.describe Whodunit::Generator do
  let(:test_dir) { "test-rails-app" }
  let(:config_dir) { "#{test_dir}/config" }
  let(:initializers_dir) { "#{test_dir}/config/initializers" }
  let(:initializer_file) { "#{test_dir}/config/initializers/whodunit.rb" }

  before do
    # Clean up any existing test directory
    FileUtils.rm_rf(test_dir)
  end

  after do
    # Clean up test directory after each test
    FileUtils.rm_rf(test_dir)
  end

  describe ".install_initializer" do
    context "in a Rails application" do
      before do
        # Create mock Rails app structure
        FileUtils.mkdir_p(config_dir)
        File.write("#{config_dir}/application.rb", "# Mock Rails application")
        Dir.chdir(test_dir)
      end

      after do
        Dir.chdir("..")
      end

      it "creates the initializer file" do
        # Capture output to avoid cluttering test output
        expect { described_class.install_initializer }.to output(%r{Generated config/initializers/whodunit\.rb}).to_stdout

        expect(File.exist?("config/initializers/whodunit.rb")).to be true
      end

      it "creates the initializers directory if it doesn't exist" do
        expect { described_class.install_initializer }.to output(%r{Creating config/initializers}).to_stdout

        expect(Dir.exist?("config/initializers")).to be true
      end

      it "generates the correct file header and structure" do
        described_class.install_initializer

        content = File.read("config/initializers/whodunit.rb")

        expect(content).to include("# Whodunit.configure do |config|")
        expect(content).to include("# end")
        expect(content).to include("# frozen_string_literal: true")
        expect(content).to include("# This file was generated by `whodunit install` command.")
      end

      it "includes all basic configuration options" do
        described_class.install_initializer

        content = File.read("config/initializers/whodunit.rb")

        expect(content).to include("#   config.user_class = 'Account'             # Default: 'User'")
        expect(content).to include("#   config.creator_column = :created_by_id    # Default: :creator_id")
        expect(content).to include("#   config.updater_column = :updated_by_id    # Default: :updater_id")
        expect(content).to include("#   config.deleter_column = :deleted_by_id    # Default: :deleter_id")
        expect(content).to include("#   config.soft_delete_column = :discarded_at # Default: nil")
      end

      it "includes data type configuration options" do
        described_class.install_initializer

        content = File.read("config/initializers/whodunit.rb")

        expect(content).to include("#   config.column_data_type = :integer       # Default: :bigint")
        expect(content).to include("#   config.creator_column_type = :string     # Default: nil")
        expect(content).to include("#   config.updater_column_type = :uuid       # Default: nil")
        expect(content).to include("#   config.deleter_column_type = :integer    # Default: nil")
      end

      context "when initializer already exists" do
        before do
          FileUtils.mkdir_p("config/initializers")
          File.write("config/initializers/whodunit.rb", "# Existing content")
        end

        it "prompts for overwrite confirmation" do
          # Mock user input to decline overwrite
          allow($stdin).to receive(:gets).and_return("n\n")

          expect { described_class.install_initializer }.to output(/already exists/).to_stdout
                                                                                    .and raise_error(SystemExit)
        end
      end
    end

    context "outside a Rails application" do
      before do
        Dir.chdir(test_dir) if Dir.exist?(test_dir)
      end

      after do
        Dir.chdir("..") if Dir.exist?(test_dir)
      end

      it "shows an error message" do
        # Create directory but no Rails app
        FileUtils.mkdir_p(test_dir)
        Dir.chdir(test_dir)

        expect { described_class.install_initializer }.to output(/doesn't appear to be a Rails application/).to_stdout
                                                                                                            .and raise_error(SystemExit)
      end
    end
  end

  describe ".help_message" do
    it "returns helpful usage information" do
      help = described_class.help_message

      expect(help).to include("Whodunit - Lightweight creator/updater/deleter tracking")
      expect(help).to include("whodunit install")
      expect(help).to include("whodunit help")
      expect(help).to include("Generate config/initializers/whodunit.rb")
      expect(help).to include("https://github.com/kanutocd/whodunit")
    end
  end
end
